name: CI for Churn Streamlit App

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Health Check
      run: |
        python -m compileall app.py  # Check for syntax errors
        echo "✅ Python syntax check passed!"

    - name: Optional — Streamlit Test Launch
      run: |
        streamlit run app.py --server.headless true &
        sleep 10
        curl -I http://localhost:8501 || echo "⚠️ Streamlit failed to respond"
